default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV["DEVDB"] %>

test:
  <<: *default
  database:  <%= ENV["TESTDB"] %>

production:
  url: <%= ENV["DATABASE_URL"] %>
